# Generated by Django 3.1.1 on 2020-09-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='symptoms',
            field=models.TextField(default=''),
        ),
    ]
